gitops-runtime:
  global:
    codefresh:
      accountId: 65a913bcf04bd9d21f42662d
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
  argo-cd:
    controller:
      replicas: 1
      image:
        tag: v2.8-2024.02.13-ee378953a
    server:
      image:
        tag: v2.8-2024.02.13-ee378953a
