gitops-runtime:
  global:
    codefresh:
      accountId: 65a913bcf04bd9d21f42662d
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
